NETWORK_PASSPHRASE="Pi Testnet"

[DOCUMENTATION]
ORG_NAME="ScoutMe"
ORG_URL="https://scoutme-sp.netlify.app"
ORG_DESCRIPTION="ScoutMe Token for sports talent ecosystem"
ORG_LOGO="https://scoutme-sp.netlify.app/image/logo/logo.png"

[[CURRENCIES]]
code="SMTK"
issuer="GDOU4DACEIG4CFJYQ4I4FNG3QXNQEUWFS7VFNDPDQ44DB2AAEWWDEY5L"
name="ScoutMe Token"
desc="ScoutMe token for sports talent ecosystem"
display_decimals=2
image="https://scoutme-sp.netlify.app/image/logo/logo.png"
